#!/usr/bin/env python3
"""
whitelist-audit —— 规范 §4.4 季度白名单审计

输入: PATCHES.yaml (auto-generated by sync-manifest)
输出:
  - 列出所有 status=whitelisted 的 patch
  - 标出 whitelist_reason <30 字符的 → fail
  - 标出"携带 ≥6 个月未重新评估"的项(基于 first_whitelested 字段)

用法:
  python3 tools/whitelist-audit.py
  python3 tools/whitelist-audit.py --strict    # 异常项 exit 1
"""
import argparse
import datetime
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
PATCHES = ROOT / "PATCHES.yaml"
REASON_MIN = 30
STALE_DAYS = 180


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--strict", action="store_true")
    args = ap.parse_args()

    if not PATCHES.exists():
        print("PATCHES.yaml 不存在,先跑 python3 tools/sync-manifest.py --write", file=sys.stderr)
        return 2

    m = yaml.safe_load(PATCHES.read_text(encoding="utf-8"))
    items = [p for p in m.get("patches", []) if p.get("status") == "whitelisted"]

    today = datetime.date.today()
    fail = 0
    warn = 0

    print("=== 白名单审计 (规范 §4.4) ===")
    print(f"生成时间: {datetime.datetime.now().isoformat(timespec='seconds')}")
    print(f"白名单 patch 数: {len(items)}")
    print(f"reason 字数下限: {REASON_MIN}")
    print(f"陈旧阈值: 携带 ≥{STALE_DAYS} 天未评估")
    print()

    if not items:
        print("✓ 无白名单 patch,审计通过")
        return 0

    print(f"{'patch.name':<55} {'跨版本':<25} {'reason 长度':>10} {'verdict'}")
    print("-" * 100)
    for it in items:
        name = it["name"]
        versions = " / ".join(a["version"].removeprefix("redis-") for a in it["applies_to"])
        reason = (it.get("whitelist_reason") or "").strip()
        rl = len(reason)
        verdict = []
        if rl < REASON_MIN:
            verdict.append(f"✗ reason {rl}<{REASON_MIN} 字符")
            fail += 1
        else:
            verdict.append(f"⚠ 待季度评审 (建议 {today.isoformat()})")
            warn += 1
        print(f"{name:<55} {versions:<25} {rl:>10}  {' | '.join(verdict)}")

    print()
    if fail > 0:
        print(f"✗ {fail} 个白名单 patch reason <{REASON_MIN} 字符")
        if args.strict:
            return 1
    else:
        print(f"✓ 所有白名单 patch reason 字数符合要求 (warn={warn})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
